name: Build Release Candidates

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Build Linux Release Candidate
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Linux Release Candidate
        run: npm run action src/electron/build linux -- --buildMode=release

      - name: Upload Linux Release Candidate
        uses: actions/upload-artifact@v2
        with:
          name: client_linux_release_${{ github.sha }}
          path: build/dist
          if-no-files-found: error
  android:
    name: Build Android Release Candidate
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    environment: Client Android Release
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Setup Android
        run: bash ./tools/build/setup_linux_android.sh
        
      # - name: Install Homebrew
      #   run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
      - name: Install RubyGems
        run: |
          sudo apt-get install rubygems
          sudo gem install bundler

      - name: Build Android Release Candidate
        run: npm run action fastlane/build -- --buildMode=release

      # - name: Upload Android Release Candidate
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: client_android_release_${{ github.sha }}
      #     path: platforms/android/app/build/outputs
      #     if-no-files-found: error
